# Generated by Django 2.2.6 on 2019-10-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atritributos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('idVariavel', models.IntegerField()),
                ('inicioBase', models.IntegerField()),
                ('fimBase', models.IntegerField()),
                ('inicioNucleo', models.IntegerField()),
                ('fimNucleo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='variavel',
            name='flObjetivo',
            field=models.BooleanField(default=False),
        ),
    ]
