# Generated by Django 2.2.6 on 2019-11-04 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy', '0002_auto_20191029_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atritributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('inicioBase', models.IntegerField()),
                ('fimBase', models.IntegerField()),
                ('inicioNucleo', models.IntegerField()),
                ('fimNucleo', models.IntegerField()),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='fuzzy.Variavel')),
            ],
        ),
        migrations.DeleteModel(
            name='Atritributos',
        ),
    ]
