# Generated by Django 2.2.6 on 2019-11-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy', '0003_auto_20191104_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atritributo',
            new_name='Atributo',
        ),
    ]
